Plugin 'yamafaktory/lumberjack.vim'
Plugin 'CruizeMissile/Revolution.vim'
Plugin 'ajh17/Spacegray.vim'
Plugin 'blerins/flattown'
Plugin 'whatyouhide/vim-gotham'
Plugin 'duythinht/vim-coffee'
Plugin 'svjunic/RadicalGoodSpeed.vim'
